credentials:
  usernames:
    victor:
      email: victor@aberration.com
      name: Victor
      password: $2b$12$.ejUPQtRJR9cLgZd.e7fUeBpUFf5gXT/9RwXsZNCKhvWuT96wsywK
    jin:
      email: jin@aberration.com
      name: Jin
      password: $2b$12$4V.TcJgshhgAT62U4rgKEuYiI2LBKnaeDuwzLuTMi9xlkLLgu3zy6
cookie:
  expiry_days: 30
  key: sentinel_signature_key # Must be string
  name: sentinel_cookie_name
preauthorized:
  emails:
